@dominio = http://localhost:3000
@uid=67d2134192e8a897b6d1f3ed


### create mesas
POST {{dominio}}/api/v1/mesas
Content-Type: application/json

{
  "numero": 4,
  "estado": "libre"
}


### get usuario
GET {{dominio}}/api/v1/usuarios/{{uid}}

### post de producto
POST {{dominio}}/api/v1/productos
Content-Type: application/json

{
    "name": "Philadelphia Roll",
    "descripcion": "Roll con salmón, queso crema y pepino.",
    "precio": 16,
    "img": "imgprod-2025-07-06T00-20-23-994Z.jpg",
    "tipo": "rolls"
}

### get producto
GET {{dominio}}/api/v1/productos/{{uid}}

### get productos
GET {{dominio}}/api/v1/productos